# Generated by Django 3.2.3 on 2021-07-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0003_myclothes_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclothes',
            name='thumbnail',
        ),
    ]
