# Generated by Django 3.2.3 on 2021-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0004_remove_myclothes_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclothes',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
