# Generated by Django 3.2.3 on 2021-07-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0006_auto_20210703_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclothes',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
