# Generated by Django 3.2.3 on 2021-07-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0007_auto_20210703_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclothes',
            name='thumbnail',
            field=models.ImageField(blank=True, default="{%static 'images/blank.png' %}", null=True, upload_to='images/'),
        ),
    ]
