# Generated by Django 3.2.3 on 2021-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0009_alter_myclothes_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclothes',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
