# Generated by Django 3.2.3 on 2021-07-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0010_myclothes_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclothes',
            name='weather',
            field=models.CharField(choices=[('sunny', '맑음'), ('cloud', '흐림'), ('rain', '비'), ('snow', '눈')], default='', max_length=20),
        ),
    ]
