# Generated by Django 3.2.5 on 2021-07-14 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0013_alter_myclothes_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclothes',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 14, 21, 20, 514077)),
        ),
    ]
