# Generated by Django 3.2.4 on 2021-07-02 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=20)),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=2)),
                ('age', models.IntegerField(default='')),
                ('height', models.IntegerField(default='')),
                ('bodyForm', models.CharField(choices=[('마름', '마름'), ('보통', '보통'), ('과체중', '과체중')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
                'db_table': 'user_profile',
                'ordering': ['id'],
            },
        ),
    ]
