# Generated by Django 3.2.3 on 2021-07-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='view_count',
        ),
    ]
