# Generated by Django 3.2.3 on 2021-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210703_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
