# Generated by Django 3.2.3 on 2021-07-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
